// aroma.go
// hashmaps of aroma specific addresses
package main

type AromaSource struct{}

type AddressRange struct {
	Start uint32 `json:"start"`
	End   uint32 `json:"end`
}

var AddressMap = map[string]uint32{
	"X Position":                    0x1096EF48,
	"Y Position":                    0x1096EF4C,
	"Z Position":                    0x1096EF50,
	"Speed Angle":                   0x1096EF0A,
	"Facing Angle":                  0x1096EF12,
	"Air Meter":                     0x10976dfe,
	"Current Stage":                 0x109763E4,
	"Current Room":                  0x10978CF8,
	"Current Spawn":                 0x109763ED,
	"Current Layer":                 0x109763EF,
	"Next Stage":                    0x109763F0,
	"Next Spawn":                    0x109763F9,
	"Next Room":                     0x109763FA,
	"Next Layer":                    0x109763FB,
	"Trigger Loading":               0x109763FC,
	"Event State":                   0x10976542,
	"Storage":                       0x10976543,
	"Fairy Fountain Get Item Value": 0x10976554,
	"Link Pointer":                  0x10976de4,
	"Gamepad Input":                 0x102F48A8,
	"Left Stick X Input":            0x102F48B4,
	"Left Stick Y Input":            0x102F48B8,
	"Right Stick X Input":           0x102F48BC,
	"Right Stick Y Input":           0x102F48C0,
	"Max Hearts":                    0x15073681,
	"Current Hearts":                0x15073683,
	"Max Magic":                     0x1506b513,
	"Current Magic":                 0x1506b514,
	"Max Bombs":                     0x1506b570,
	"Bombs":                         0x1506b56a,
	"Max Arrows":                    0x1506b56f,
	"Arrows":                        0x1506b569,
	"Rupees":                        0x1506b504,
	"Time":                          0x150736A4,
	"Soft Reset":                    0x1098f293,
	"Collision offset":              0x834,
	"Speed offset":                  0x6A14,
	"X Equip item":                  0x10976e6b,
	"Y Equip item":                  0x10976e6c,
	"R Equip item":                  0x10976e6d,
}

var ItemSlotMap = map[string]uint32{
	//main inventory
	"Telescope":      0x1506b53c,
	"Tingle Bottle":  0x1506b543,
	"Pictobox":       0x1506b544,
	"Spoils Bag":     0x1506b540,
	"Bait Bag":       0x1506b547,
	"Delivery Bag":   0x1506b54e,
	"Grappling Hook": 0x1506b53f,
	"Boomerang":      0x1506b541,
	"Skull Hammer":   0x1506b550,
	"Deku Leaf":      0x1506b542,
	"Bow":            0x1506b548,
	"Iron Boots":     0x1506b545,
	"Bombs":          0x1506b549,
	"Hookshot":       0x1506b54f,
	"Magic Armor":    0x1506b546,
	"Bottle 1":       0x1506b54a,
	"Bottle 2":       0x1506b54b,
	"Bottle 3":       0x1506b54c,
	"Bottle 4":       0x1506b54d,

	//key items
	"Sword":           0x1506b50e,
	"Shield":          0x1506b50f,
	"Wind Waker":      0x1506b53e,
	"Hero's Charm":    0x1506b5b8,
	"Sail":            0x1506b53d,
	"Power Bracelets": 0x1506b5b6,
	"Triforce":        0x1506b5be,
	"Pearls":          0x1506b5bf,
	"Songs":           0x1506b5bd,
}

var CollisionTypesMap = map[string]uint32{
	"Normal":        0x0,
	"Chest Storage": 0x4,
	"Door Cancel":   0x4004,
}

var ItemValuesMap = map[string]uint32{
	"Bait Bag":                     0x2c,
	"Bombs":                        0x31,
	"Boomerang":                    0x2d,
	"Deku Leaf":                    0x34,
	"Delivery Bag":                 0x30,
	"Pictobox":                     0x23,
	"Deluxe Pictobox":              0x26,
	"Grappling Hook":               0x25,
	"Hero's Bow":                   0x27,
	"Fire & Ice Arrows":            0x35,
	"Light Arrows":                 0x36,
	"Hero's Charm":                 0x01,
	"Hero's Shield":                0x3b,
	"Mirror Shield":                0x3c,
	"Hero's Sword":                 0x38,
	"Master Sword ":                0x39,
	"Master Sword (Half Charged)":  0x3a,
	"Master Sword (Fully Charged)": 0x3e,
	"Hookshot":                     0x2f,
	"Iron Boots":                   0x29,
	"Magic Armor":                  0x2a,
	"Power Bracelets":              0x28,
	"Skull Hammer":                 0x33,
	"Spoils Bag":                   0x24,
	"Telescope":                    0x20,
	"Tingle Bottle":                0x21,
	"Wind Waker":                   0x22,
	"Bottle":                       0x50,
	"Red Elixir":                   0x51,
	"Green Elixir":                 0x52,
	"Blue Elixir":                  0x53,
	"Soup Half":                    0x54,
	"Soup":                         0x55,
	"Water":                        0x56,
	"Fairy":                        0x57,
	"Pollen":                       0x58,
	"Forest Water":                 0x59,
	"Normal Sail":                  0x78,
	"Swift Sail":                   0x77,
	"Winds Requiem":                0b00000001,
	"Ballad Of Gales":              0b00000010,
	"Command Melody":               0b00000100,
	"Earth Gods Lyrics":            0b00001000,
	"Wind Gods Aria":               0b00010000,
	"Song Of Passing":              0b00100000,
	"Triforce":                     0b11111111, //each bit is a triforce piece
	"Nayrus Pearl":                 0b00000001,
	"Dins Pearl":                   0b00000010,
	"Farores Pearl":                0b00000100,
	"Town Flower":                  0x8c,
	"Sea Flower":                   0x8d,
	"Exotic Flower":                0x8e,
	"Hero's Flag":                  0x8f,
	"Big Catch Flag":               0x90,
	"Big Sale Flag":                0x91,
	"Pinwheel":                     0x92,
	"Sickle Moon Flag":             0x93,
	"Skull Tower Idol":             0x94,
	"Fountain Idol":                0x95,
	"Postman Statue":               0x96,
	"Shop Guru Statue":             0x97,
	"Father's Letter":              0x98,
	"Note To Mom":                  0x99,
	"Maggie's Letter":              0x9a,
	"Moblin's Letter":              0x9b,
	"Cabana Deed":                  0x9c,
	"Complimentary Id":             0x9d,
	"Fill Up Coupon":               0x9e,
	"Dungeon Keys":                 0x0a,
	"Dungeon Map":                  0b00000001,
	"Dungeon Compass":              0b00000010,
	"Dungeon Boss Key":             0b00000100,
}

var AreasMap = map[string]string{
	"Outset Island - Forest":              "A_mori",
	"Invisible Island":                    "A_nami",
	"Pirate Ship - Deck":                  "A_umikz",
	"Link's Oasis":                        "Abesso",
	"Submarine Interior":                  "Abship",
	"Dragon Roost Island - Spring":        "Adanmae",
	"Tower of Gods - Cutscene":            "ADMumi",
	"Pirate Ship - Interior":              "Asoko",
	"Dragon Roost Island - Mail Center":   "Atorizk",
	"Bomb Island - Cave":                  "Cave01",
	"Star Island - Cave":                  "Cave02",
	"Cliff Plateau Isles - Cave":          "Cave03",
	"Rock Spire Isle - Cave":              "Cave04",
	"Horseshoe Island - Cave":             "Cave05",
	"Outset Island - Unused Cave":         "Cave06",
	"Pawprint Isle - Wizzrobe Cave":       "Cave07",
	"Savage Labyrinth - Beginning":        "Cave09",
	"Savage Labyrinth - Empty":            "Cave10",
	"Savage Labyrinth - Another Empty":    "Cave11",
	"Dragon Roost Island - Komali's Room": "Comori",
	"Outset Island - Test":                "DmSpot0",
	"Earth Temple - Entrance":             "Edaichi",
	"Wind Temple - Entrance":              "Ekaze",
	"End Game Cutscene":                   "ENDumi",
	"Northern Fairy Island - Fairy":       "Fairy01",
	"Eastern Fairy Island - Fairy":        "Fairy02",
	"Western Fairy Island - Fairy":        "Fairy03",
	"Outset Island - Forest - Fairy":      "Fairy04",
	"Thorned Fairy Island - Fairy":        "Fairy05",
	"Southern Fairy Island - Fairy":       "Fairy06",
	"Gallery - Great Sea Figurines":       "figureA",
	"Gallery - Windfall Island Figurines": "figureB",
	"Gallery - Outset Island Figurines":   "figureC",
	"Gallery - Boss Figurines":            "figureD",
	"Gallery - Enemy Figurines":           "figureE",
	"Gallery - DRC Figurines":             "figureF",
	"Gallery - Forest Haven Figurines":    "figureG",
	"Ganon's Tower - Entrance":            "GanonA",
	"Ganon's Tower - DRC Trail":           "GanonB",
	"Ganon's Tower - WT Trail":            "GanonD",
	"Ganon's Tower - FW Trail":            "GanonD",
	"Ganon's Tower - ET Trail":            "GanonE",
	"Ganon's Tower - Maze":                "GanonJ",
	"Ganon's Tower - Ganon's Room":        "GanonK",
	"Ganon's Tower - Staircase to Ganon":  "GanonL",
	"Ganon's Tower - Center":              "GanonM",
	"Ganon's Tower - Staircase to Center": "GanonN",
	"Ganon's Tower - Final Fight":         "GTower",
	"Hyrule Castle - Interior":            "Hyroom",
	"Hyrule Castle - Exterior":            "Hyrule",
	"Bomb Island - Cave Test":             "ITest61",
	"Ice Ring Isle - Grotto":              "ITest62",
	"Shark Island - Cave":                 "ITest63",
	"Windfall Island - Minigame House":    "Kaisen",
	"Unused Fire Mountain":                "kazan",
	"Wind Temple":                         "kaze",
	"Wind Temple - Boss Room":             "kazeB",
	"Wind Temple - Miniboss Room":         "kazeMB",
	"Hyrule Castle - Basement":            "kenroom",
	"Forbidden Woods - Boss Room":         "kinBOSS",
	"Forbidden Woods":                     "kindan",
	"Forbidden Woods - Miniboss Room":     "kinMB",
	"Outset Island - Link's House":        "LinkRM",
	"Outset Island - Basement":            "LinkUG",
	"Earth Temple":                        "M_Dai",
	"Earth Temple - Boss Room":            "M_DaiB",
	"Dragon Roost Cavern - Boss Room":     "M_DragB",
	"Dragon Roost Cavern":                 "M_NewD2",
	"Forsaken Fortress - Ganon's Lair":    "M2ganon",
	"Forsaken Fortress - Interior 1":      "ma2room",
	"Forsaken Fortress - Interior 2":      "ma3room",
	"Forsaken Fortress - Interior 3":      "majroom",
	"Forsaken Fortress - Exterior":        "MajyuE",
	"Inside Ice Ring Isle":                "MiniHyo",
	"Inside Fire Mountain":                "MiniKaz",
	"Forsaken Fortress - Helmroc's Room":  "Mjtower",
	"Unused Temple Island":                "Mukao",
	"File Select":                         "Name",
	"Windfall Island - School of Joy":     "Nitiyou",
	"Windfall Island - Bomb Shop":         "Obombh",
	"Beedle's Shop Ship":                  "Obshop",
	"Boating Course":                      "Ocean",
	"Windfall Island - Lenzo's Studio":    "Ocmera",
	"Forest Haven - Bomb Shop":            "Ocrogh",
	"Outset Island - Orca's House":        "Ojhous",
	"Outset Island - Sturgeon's House":    "Ojhous2",
	"Outset Island - Mesa's House":        "Omasao",
	"Forest Haven - Interior":             "Omori",
	"Outset Island - Abe's House":         "Onobuta",
	"Windfall Island - Cafe Bar":          "Opub",
	"Windfall Island - Auction House":     "Orichh",
	"Forest Haven - Behind Waterfall":     "Otkura",
	"Windfall Island - Potion Shop":       "Pdrgsh",
	"Nintendo Gallery":                    "Pfigure",
	"Outset Island - Jabun's Cavern":      "Pjavdou",
	"Windfall Island - Prison":            "Pnezumi",
	"Ghost Ship":                          "PShip",
	"Submarine - Unused Room":             "PShip2",
	"Submarine - Unused Room 2":           "PShip3",
	"Great Sea":                           "sea",
	"Credits":                             "sea_E",
	"Title Screen":                        "sea_T",
	"Islet of Steel - Interior":           "ShipD",
	"Tower of Gods":                       "Siren",
	"Tower of Gods - Boss Room":           "SirenB",
	"Tower of Gods - Miniboss Room":       "SirenMB",
	"Needle Rock Isle - Cave":             "SubD42",
	"Angular Isles - Cave":                "SubD43",
	"Stonewatcher Island - Cave":          "SubD44",
	"Bomb Island - Early Cave":            "SubD51",
	"Bomb Island - Another Early Cave":    "SubD71",
	"Tingle's Paint Room":                 "tincle",
	"Stonewatcher Island - Triforce Cave": "TF_01",
	"Overlook Island - Triforce Cave":     "TF_02",
	"Bird's Peak Rock - Triforce Cave":    "TF_03",
	"Link's Oasis - Triforce Cave":        "TF_04",
	"Dragon Roost Island - Cave":          "TF_06",
	"Pawprint Isle - Cave":                "TyuTyu",
	"Diamond Steppe Island - Cave":        "WarpD",
	"Ganon's Tower - DRC Trail Boss":      "Xboxx0",
	"Ganon's Tower - FW Trail Boss":       "Xboss1",
	"Ganon's Tower - ET Trail Boss":       "Xboss2",
	"Ganon's Tower - WT Trail Boss":       "Xboss3",
}

var InputsValueMap = map[string]uint32{
	"minusButton":     0x4,
	"plusButton":      0x8,
	"rButton":         0x10,
	"lButton":         0x20,
	"zrButton":        0x40,
	"zlButton":        0x80,
	"dpadDownButton":  0x100,
	"dpadUpButton":    0x200,
	"dpadRightButton": 0x400,
	"dpadLeftButton":  0x800,
	"yButton":         0x1000,
	"xButton":         0x2000,
	"bButton":         0x4000,
	"aButton":         0x8000,
	"l3Button":        0x40000,
	"r3Button":        0x20000,
	"tvButton":        0x10000,
}

var AddressRangeMap = map[string]AddressRange{
	"Scene Flags":        {Start: 0x15073DF8, End: 0x15073E18}, // should be different for aroma ill look into that
	"Global Flags":       {Start: 0x1506bb24, End: 0x1506BB63},
	"Ocean Color":        {Start: 0x26917424, End: 0x26917428}, // should be different for aroma ill look into that
	"Spoils Bag Slots":   {Start: 0x1506b576, End: 0x1506b57d},
	"Bait Bag Slots":     {Start: 0x1506b57e, End: 0x1506b585},
	"Delivery Bag Slots": {Start: 0x1506b586, End: 0x1506b58d},
}

func (a AromaSource) GetData() map[string]any {
	return map[string]any{
		"general":         FormatAddressMap(AddressMap),
		"slots":           FormatAddressMap(ItemSlotMap),
		"items":           FormatAddressMap(ItemValuesMap),
		"inputs":          FormatAddressMap(InputsValueMap),
		"collision_types": FormatAddressMap(CollisionTypesMap),
		"ranges":          FormatRangeMap(AddressRangeMap),
		"areas":           AreasMap,
	}
}
